apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: tomcat
    name: tomcat
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    selector:
      io.kompose.service: tomcat
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: tomcat
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: tomcat
      spec:
        containers:
        - image: bitnami/tomcat:latest
          name: tomcat
          ports:
          - containerPort: 8080
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/tomcat
            name: tomcat-tomcat-data
        restartPolicy: Always
        volumes:
        - name: tomcat-tomcat-data
          persistentVolumeClaim:
            claimName: tomcat-tomcat-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: tomcat-tomcat-data
    name: tomcat-tomcat-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}

